project:
  type: website

website:
  title: "blog"
  site-url: https://truonghm.github.io/
  description: "TruongHM's homepage"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/truonghm
      - icon: linkedin
        href: https://www.linkedin.com/in/hmtrg/
format:
  html:
    theme: zephyr
    css: styles.css
execute:
  freeze: auto